dist: xenial
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - python3-pip
      - python3-setuptools
      - libclang-7-dev
      - llvm-7
      - llvm-7-dev
      - libboost-all-dev
      - texlive-full

before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - which -a llvm-config
  - which -a llvm-config-7
  - /usr/bin/llvm-config --cxxflags
  - /usr/bin/llvm-config-7 --cxxflags
  - pip3 install --user --upgrade pip
  - pip3 install --user meson ninja

script:
  - mkdir build && cd build && meson .. && cd .. && ninja -C build
  - pdflatex thesis.tex
