dist: xenial
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - python3-pip
      - python3-setuptools
      - libclang-7-dev
      - clang-7
      - llvm-7
      - llvm-7-dev
      - libboost-all-dev
      - texlive-full
      - rubber

before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - mkdir -p $HOME/.local/bin
  - ln -s /usr/bin/clang++-7 $HOME/.local/bin/clang++
  - ln -s /usr/bin/clang-7 $HOME/.local/bin/clang
  - pip3 install --user --upgrade pip
  - pip3 install --user --requirement requirements.txt

script:
  - mkdir build && cd build && meson .. && cd ..
  - ninja -C build
  - ninja -C build robot
